// Importación de tipos y componentes necesarios desde Next.js y otras dependencias
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Image from 'next/image';

// Configuración de la fuente 'Inter' con un subconjunto específico
const inter = Inter({ subsets: ['latin'] });

// Definición de metadatos para la página, útiles para SEO y configuración del proyecto
export const metadata: Metadata = {
  title: 'Frontend MeLi',
  description: 'Generated by create next app',
};

// Componente RootLayout que actúa como layout principal para la aplicación
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // Estructura HTML
    <html lang="es">
      {/* Link al favicon del sitio */}
      <link rel="icon" href="../app/favicon.ico" />
      <body>
        {/* Encabezado del sitio web */}
        <header className='justify-center items-center h-24 bg-yellow-300 flex'>
          {/* Formulario de búsqueda que redirige a la página /items */}
          <form action="/items" className='flex max-w-screen-xl'>
            <a href="/">
              {/* Logo del sitio que también sirve como botón de inicio */}
              <img src="/lg.png" alt="Volver al home" title='volver al home' />
            </a>
            {/* Campo de entrada para la búsqueda */}
            <input className='inputGeneral text-black px-2' type="text" name='search' placeholder='Haga click en buscar producto...' />
            {/* Botón de búsqueda */}
            <button className='searchGeneral' type='submit'>
              <img src='/search.png' alt="Buscar"/>
            </button>
          </form>
        </header>
        {/* Contenedor principal donde se renderizan los componentes hijos */}
        <main className="layout">
          {children}
        </main>
      </body>
    </html>
  );
}
