import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
title: 'Frontend MeLi',
description: 'Generated by create next app',

}

export default function RootLayout({
children,
}: {
children: React.ReactNode
}) {
return (
<html lang="en">
<link rel="icon" href="../app/favicon.ico" />
<body>
  <header className='justify-center items-center h-24 bg-yellow-300 flex'>
    <form action="/items" className=' flex max-w-screen-xl'>
        <a href="/">
          <img src="/lg.png" alt="Volver al home" title='volver al home' />
        </a>
          <input className=' inputGeneral  text-black px-2' type="text" name='search' placeholder='Haga click en buscar producto...' />
          <button className='searchGeneral' type='submit'><img src='/search.png' alt="Buscar"/></button>
    </form>
  </header>
  <main className="layout">
    {children}
  </main>
  
</body>

</html>
)
}